/*

 UNDERGROUND_TILESET.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : Tile-count as Constant.
  Tile size            : 8 x 8
  Tiles                : 0 to 255

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __underground_tileset_h_INCLUDE
#define __underground_tileset_h_INCLUDE

/* Bank of tiles. */
#define underground_tilesetBank 4
/* Start of tile array. */
extern const void __bank_underground_tileset;
extern const unsigned char underground_tileset[];
#define underground_tilesetLen 256

#endif

/* End of UNDERGROUND_TILESET.H */
