/*

 UNDERGROUND_TILEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 4
   Map size      : 64 x 64
   Tile set      : underground.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __underground_tilemap_h_INCLUDE
#define __underground_tilemap_h_INCLUDE

#define underground_tilemapWidth 64
#define underground_tilemapHeight 64
#define underground_tilemapBank 4

extern const void __bank_underground_tilemap;
extern const unsigned char underground_tilemap[];

#endif

/* End of UNDERGROUND_TILEMAP.H */
