/*

 SNAKE_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : Tile-count as Constant.
  Tile size            : 8 x 8
  Tiles                : 0 to 39

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __snake_tiles_h_INCLUDE
#define __snake_tiles_h_INCLUDE

/* Bank of tiles. */
#define gfx_snake_tilesBank 0
/* Start of tile array. */
extern const unsigned char gfx_snake_tiles[];
#define gfx_snake_tilesLen 40

#endif

/* End of SNAKE_TILES.H */
