/*

 TILESET.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : Tile-count as Constant.
  Tile size            : 8 x 8
  Tiles                : 0 to 255

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __tileset_h_INCLUDE
#define __tileset_h_INCLUDE

/* Bank of tiles. */
#define tilesetBank 0
/* Start of tile array. */
extern const unsigned char tileset[];
#define tilesetLen 256

#endif

/* End of TILESET.H */
