/*

 TILEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 64 x 64
   Tile set      : Z:\home\irenee\work\dev\gb\snake\res\tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __tilemap_h_INCLUDE
#define __tilemap_h_INCLUDE

#define tilemapWidth 64
#define tilemapHeight 64
#define tilemapBank 0

extern const unsigned char tilemap[];

#endif

/* End of TILEMAP.H */
