/*

 GFX_GARDEN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 64 x 64
   Tile set      : background.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __gfx_garden_h_INCLUDE
#define __gfx_garden_h_INCLUDE

#define gfx_gardenWidth 64
#define gfx_gardenHeight 64
#define gfx_gardenBank 0

extern const unsigned char gfx_garden[];

#endif

/* End of GFX_GARDEN.H */
