/*

 GFX_SPRITES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : Tile-count as Constant.
  Tile size            : 8 x 8
  Tiles                : 0 to 39

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __gfx_sprites_h_INCLUDE
#define __gfx_sprites_h_INCLUDE

/* Bank of tiles. */
#define gfx_spritesBank 0
/* Start of tile array. */
extern const unsigned char gfx_sprites[];
#define gfx_spritesLen 40

#endif

/* End of GFX_SPRITES.H */
