// This file was generated by img2gb, DO NOT EDIT

#ifndef _TITLESCREEN_TILESET_H
#define _TITLESCREEN_TILESET_H

extern const UINT8 TITLESCREEN_TILESET[];
#define TITLESCREEN_TILESET_TILE_COUNT 204


#endif
