/*

 CLOUDS_TILEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 3
   Map size      : 64 x 64
   Tile set      : Z:\home\irenee\work\dev\gb\snake\res\level2_clouds\clouds.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __clouds_tilemap_h_INCLUDE
#define __clouds_tilemap_h_INCLUDE

#define clouds_tilemapWidth 64
#define clouds_tilemapHeight 64
#define clouds_tilemapBank 3

extern const void __bank_clouds_tilemap;
extern const unsigned char clouds_tilemap[];

#endif

/* End of CLOUDS_TILEMAP.H */
