/*

 CLOUDS_TILESET.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : Tile-count as Constant.
  Tile size            : 8 x 8
  Tiles                : 0 to 255

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __clouds_tileset_h_INCLUDE
#define __clouds_tileset_h_INCLUDE

/* Bank of tiles. */
#define clouds_tilesetBank 3
/* Start of tile array. */
extern const void __bank_clouds_tileset;
extern const unsigned char clouds_tileset[];
#define clouds_tilesetLen 256

#endif

/* End of CLOUDS_TILESET.H */
