#ifndef GRAPHICS_H
#define GRAPHICS_H

#define GFX_EMPTY_TILE_ID 0U

#define GFX_SNAKE_HEAD_NW_TILE_ID 168U
#define GFX_SNAKE_HEAD_NE_TILE_ID 170U
#define GFX_SNAKE_HEAD_SW_TILE_ID 169U
#define GFX_SNAKE_HEAD_SE_TILE_ID 171U

#define GFX_SNAKE_TAIL_NW_TILE_ID 168U
#define GFX_SNAKE_TAIL_NE_TILE_ID 170U
#define GFX_SNAKE_TAIL_SW_TILE_ID 169U
#define GFX_SNAKE_TAIL_SE_TILE_ID 171U

#define GFX_SNAKE_CORNER_WNW_TILE_ID 173U
#define GFX_SNAKE_CORNER_NW_TILE_ID 172U
#define GFX_SNAKE_CORNER_NNW_TILE_ID 180U

#define GFX_SNAKE_CORNER_NNE_TILE_ID 182U
#define GFX_SNAKE_CORNER_NE_TILE_ID 174U
#define GFX_SNAKE_CORNER_ENE_TILE_ID 175U

#define GFX_SNAKE_CORNER_ESE_TILE_ID 178U
#define GFX_SNAKE_CORNER_SE_TILE_ID 179U
#define GFX_SNAKE_CORNER_SSE_TILE_ID 183U

#define GFX_SNAKE_CORNER_SSW_TILE_ID 181U
#define GFX_SNAKE_CORNER_SW_TILE_ID 177U
#define GFX_SNAKE_CORNER_WSW_TILE_ID 176U

#define GFX_SNAKE_BODY_N_TILE_ID 166U
#define GFX_SNAKE_BODY_S_TILE_ID 167U
#define GFX_SNAKE_BODY_W_TILE_ID 164U
#define GFX_SNAKE_BODY_E_TILE_ID 165U

#define GFX_SNAKE_BODY_FILL_TILE_ID 162U

#define GFX_OFFSET_CAPABLE_TILE_ID 160U

#define GFX_SNAKE_OFFSET_0 0U
#define GFX_SNAKE_OFFSET_1 24U
#define GFX_SNAKE_OFFSET_2 48U
#define GFX_SNAKE_OFFSET_3 72U

#endif // GRAPHICS_H
