#ifndef GRAPHICS_H
#define GRAPHICS_H

#define GFX_EMPTY_TILE_ID 0U

#define GFX_SNAKE_HEAD_NW_TILE_ID 192U
#define GFX_SNAKE_HEAD_NE_TILE_ID 194U
#define GFX_SNAKE_HEAD_SW_TILE_ID 193U
#define GFX_SNAKE_HEAD_SE_TILE_ID 195U

#define GFX_SNAKE_TAIL_NW_TILE_ID 192U
#define GFX_SNAKE_TAIL_NE_TILE_ID 194U
#define GFX_SNAKE_TAIL_SW_TILE_ID 193U
#define GFX_SNAKE_TAIL_SE_TILE_ID 195U

#define GFX_SNAKE_CORNER_WNW_TILE_ID 197U
#define GFX_SNAKE_CORNER_NW_TILE_ID 196U
#define GFX_SNAKE_CORNER_NNW_TILE_ID 204U

#define GFX_SNAKE_CORNER_NNE_TILE_ID 206U
#define GFX_SNAKE_CORNER_NE_TILE_ID 198U
#define GFX_SNAKE_CORNER_ENE_TILE_ID 199U

#define GFX_SNAKE_CORNER_ESE_TILE_ID 202U
#define GFX_SNAKE_CORNER_SE_TILE_ID 203U
#define GFX_SNAKE_CORNER_SSE_TILE_ID 207U

#define GFX_SNAKE_CORNER_SSW_TILE_ID 205U
#define GFX_SNAKE_CORNER_SW_TILE_ID 201U
#define GFX_SNAKE_CORNER_WSW_TILE_ID 200U

#define GFX_SNAKE_BODY_N_TILE_ID 178U
#define GFX_SNAKE_BODY_S_TILE_ID 179U
#define GFX_SNAKE_BODY_W_TILE_ID 176U
#define GFX_SNAKE_BODY_E_TILE_ID 177U

#define GFX_SNAKE_BODY_FILL_TILE_ID 190U

#define GFX_OFFSET_CAPABLE_TILE_ID 192U

#endif // GRAPHICS_H
