name: Build

on:
  - workflow_dispatch
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: snake

      - name: Get SDCC
        run: |
          # Use patched sms/gg z80 build:
          # For GBDK-2020 4.1.0
          curl -Lo sdcc.tar.bz2 https://github.com/gbdk-2020/gbdk-2020-sdcc/releases/download/sdcc-13350-patched-gbdk-4.1.0/sdcc-amd64-linux2.5-20220402-13350--sdldz80-patched-at-12539.tar.bz2
          bunzip2 sdcc.tar.bz2
          tar xf sdcc.tar

      - name: Get GBDK
        run: |
          curl -Lo gbdk.tar.gz https://github.com/gbdk-2020/gbdk-2020/releases/download/4.1.1/gbdk-linux64.tar.gz
          tar xf gbdk.tar.gz

      - name: Build
        shell: bash
        run: |
          export GBDK_HOME=`pwd`/gbdk
          pushd snake
          make
          popd

      - name: Create release tag
        run: |
          echo "RELEASE_TAG=$(date +%F)" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          draft: false
          prerelease: false
          files: snake/obj/Snake.gb
